http:
  middlewares:
    to-https:
      redirectScheme:
        scheme: https
        permanent: true

    strip-booking:
      stripPrefix:
        prefixes:
          - "/api/booking"

  routers:
    catch-http:
      entryPoints: [web]
      rule: "Host(`astrolumina.ro`)"
      middlewares: [to-https]
      service: noop

    booking:
      entryPoints: [websecure]
      rule: "Host(`astrolumina.ro`) && PathPrefix(`/api/booking`)"
      middlewares: [strip-booking]
      tls:
        certResolver: letsencrypt
      service: booking-blue

  services:
    booking-blue:
      loadBalancer:
        servers:
          - url: "http://booking-api-blue:3033"

    booking-green:
      loadBalancer:
        servers:
          - url: "http://booking-api-green:3033"

    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
